[package]
name = "bfte-node-ui"

edition.workspace = true
version.workspace = true

[dependencies]
async-trait = { workspace = true }
bfte-consensus-core = { workspace = true }
bfte-util-error = { workspace = true }
tokio = { workspace = true }
