[package]
name = "bfte-module-consensus-ctrl-effects"

edition.workspace = true
version.workspace = true

[dependencies]
bfte-consensus-core = { workspace = true }
bfte-module = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }